### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by NickHeiner** [eps1lon/esquery-cli#1]
When I run this tool, I get a crash.

Node 14:

```
λ npx esquery-cli 'CallExpression > Identifier[name="require"]:not(Program > VariableDeclaration Identifier[name="require"])' 'tools/**/*.js'
npx: installed 102 in 8.705s
file:///Users/nheiner/.npm/_npx/4856/lib/node_modules/esquery-cli/bin/esquery-cli.js:2
import { codeFrameColumns } from "@babel/code-frame";
         ^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@babel/code-frame' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from '@babel/code-frame';
const { codeFrameColumns } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Node 12:

```
λ npx esquery-cli 'CallExpression > Identifier[name="require"]:not(Program > VariableDeclaration Identifier[name="require"])' 'tools/**/*.js'
npx: installed 102 in 8.776s
Cannot use import statement outside a module
(node:4604) Warning: require() of ES modules is not supported.
require() of /Users/nheiner/.npm/_npx/4604/lib/node_modules/esquery-cli/bin/esquery-cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename esquery-cli.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/nheiner/.npm/_npx/4604/lib/node_modules/esquery-cli/package.json.
```

**Comment by eps1lon** [comment]
Thanks for the report.

Could you run `npx envinfo` when using node 14 and post the results?

Note that node 12 is not supported. I added an entry to the `engines` field but unforunately `npx` only considers this field advisory and does not throw if the version mismatches.

**Comment by NickHeiner** [comment]
Hmm, too bad that `npx` doesn't make the engine mismatch failure louder.

```
  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.10 GB / 16.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
  Managers:
    Homebrew: 3.0.6 - /usr/local/bin/brew
    pip3: 21.0.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.27.0 - /usr/local/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.0 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.56.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.2 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  Monorepos:
    Yarn Workspaces: 1.22.10
```

**Comment by eps1lon** [comment]
When I original worked on `esquery-cli` I used node `v14.16.1`. Could you check if that version works? Then I'll adjust the requirements accordingly which will probably result in a runtime check rather than the `engines` field. Though I would prefer a static check rather than a runtime check.
